package com.idata.gtd.dao;

import com.idata.gtd.entity.DepartmentEmploye;

public interface DepartmentEmployeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department_employe
     *
     * @mbg.generated Thu Jan 11 18:00:33 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department_employe
     *
     * @mbg.generated Thu Jan 11 18:00:33 CST 2018
     */
    int insert(DepartmentEmploye record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department_employe
     *
     * @mbg.generated Thu Jan 11 18:00:33 CST 2018
     */
    int insertSelective(DepartmentEmploye record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department_employe
     *
     * @mbg.generated Thu Jan 11 18:00:33 CST 2018
     */
    DepartmentEmploye selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department_employe
     *
     * @mbg.generated Thu Jan 11 18:00:33 CST 2018
     */
    int updateByPrimaryKeySelective(DepartmentEmploye record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department_employe
     *
     * @mbg.generated Thu Jan 11 18:00:33 CST 2018
     */
    int updateByPrimaryKey(DepartmentEmploye record);
}