package com.idata.gtd.dao;

import com.idata.gtd.entity.Document;

public interface DocumentMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table document
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table document
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	int insert(Document record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table document
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	int insertSelective(Document record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table document
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	Document selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table document
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	int updateByPrimaryKeySelective(Document record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table document
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	int updateByPrimaryKey(Document record);
}