package com.idata.gtd.dao;

import com.idata.gtd.entity.DucumentFile;

public interface DucumentFileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ducument_file
     *
     * @mbg.generated Thu Jan 11 17:28:31 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ducument_file
     *
     * @mbg.generated Thu Jan 11 17:28:31 CST 2018
     */
    int insert(DucumentFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ducument_file
     *
     * @mbg.generated Thu Jan 11 17:28:31 CST 2018
     */
    int insertSelective(DucumentFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ducument_file
     *
     * @mbg.generated Thu Jan 11 17:28:31 CST 2018
     */
    DucumentFile selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ducument_file
     *
     * @mbg.generated Thu Jan 11 17:28:31 CST 2018
     */
    int updateByPrimaryKeySelective(DucumentFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ducument_file
     *
     * @mbg.generated Thu Jan 11 17:28:31 CST 2018
     */
    int updateByPrimaryKey(DucumentFile record);
}