package com.idata.gtd.dao;

import com.idata.gtd.entity.ParamKey;

public interface ParamKeyMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table param_key
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table param_key
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	int insert(ParamKey record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table param_key
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	int insertSelective(ParamKey record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table param_key
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	ParamKey selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table param_key
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	int updateByPrimaryKeySelective(ParamKey record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table param_key
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	int updateByPrimaryKey(ParamKey record);
}