package com.idata.gtd.dao;

import com.idata.gtd.entity.ParamValue;

public interface ParamValueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table param_value
     *
     * @mbg.generated Thu Jan 11 17:28:31 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table param_value
     *
     * @mbg.generated Thu Jan 11 17:28:31 CST 2018
     */
    int insert(ParamValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table param_value
     *
     * @mbg.generated Thu Jan 11 17:28:31 CST 2018
     */
    int insertSelective(ParamValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table param_value
     *
     * @mbg.generated Thu Jan 11 17:28:31 CST 2018
     */
    ParamValue selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table param_value
     *
     * @mbg.generated Thu Jan 11 17:28:31 CST 2018
     */
    int updateByPrimaryKeySelective(ParamValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table param_value
     *
     * @mbg.generated Thu Jan 11 17:28:31 CST 2018
     */
    int updateByPrimaryKey(ParamValue record);
}