package com.idata.gtd.dao;

import com.idata.gtd.entity.ProjectGroup;

public interface ProjectGroupMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project_group
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project_group
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	int insert(ProjectGroup record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project_group
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	int insertSelective(ProjectGroup record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project_group
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	ProjectGroup selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project_group
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	int updateByPrimaryKeySelective(ProjectGroup record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project_group
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	int updateByPrimaryKey(ProjectGroup record);
}