package com.idata.gtd.dao;

import com.idata.gtd.entity.ProjectStage;

public interface ProjectStageMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project_stage
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project_stage
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	int insert(ProjectStage record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project_stage
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	int insertSelective(ProjectStage record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project_stage
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	ProjectStage selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project_stage
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	int updateByPrimaryKeySelective(ProjectStage record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project_stage
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	int updateByPrimaryKey(ProjectStage record);
}