package com.idata.gtd.dao;

import com.idata.gtd.entity.ProjectTag;

public interface ProjectTagMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project_tag
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project_tag
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	int insert(ProjectTag record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project_tag
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	int insertSelective(ProjectTag record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project_tag
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	ProjectTag selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project_tag
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	int updateByPrimaryKeySelective(ProjectTag record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project_tag
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	int updateByPrimaryKey(ProjectTag record);
}