package com.idata.gtd.dao;

import com.idata.gtd.entity.ProjectStaff;

public interface ProjectStaffMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_staff
     *
     * @mbg.generated Thu Jan 11 17:28:31 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_staff
     *
     * @mbg.generated Thu Jan 11 17:28:31 CST 2018
     */
    int insert(ProjectStaff record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_staff
     *
     * @mbg.generated Thu Jan 11 17:28:31 CST 2018
     */
    int insertSelective(ProjectStaff record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_staff
     *
     * @mbg.generated Thu Jan 11 17:28:31 CST 2018
     */
    ProjectStaff selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_staff
     *
     * @mbg.generated Thu Jan 11 17:28:31 CST 2018
     */
    int updateByPrimaryKeySelective(ProjectStaff record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_staff
     *
     * @mbg.generated Thu Jan 11 17:28:31 CST 2018
     */
    int updateByPrimaryKey(ProjectStaff record);
}