package com.idata.gtd.dao;

import com.idata.gtd.entity.StageCheck;

public interface StageCheckMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stage_check
     *
     * @mbg.generated Thu Jan 11 17:28:31 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stage_check
     *
     * @mbg.generated Thu Jan 11 17:28:31 CST 2018
     */
    int insert(StageCheck record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stage_check
     *
     * @mbg.generated Thu Jan 11 17:28:31 CST 2018
     */
    int insertSelective(StageCheck record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stage_check
     *
     * @mbg.generated Thu Jan 11 17:28:31 CST 2018
     */
    StageCheck selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stage_check
     *
     * @mbg.generated Thu Jan 11 17:28:31 CST 2018
     */
    int updateByPrimaryKeySelective(StageCheck record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stage_check
     *
     * @mbg.generated Thu Jan 11 17:28:31 CST 2018
     */
    int updateByPrimaryKey(StageCheck record);
}