package com.idata.gtd.dao;

import com.idata.gtd.entity.TaskLink;

public interface TaskLinkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_link
     *
     * @mbg.generated Thu Jan 11 17:28:31 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_link
     *
     * @mbg.generated Thu Jan 11 17:28:31 CST 2018
     */
    int insert(TaskLink record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_link
     *
     * @mbg.generated Thu Jan 11 17:28:31 CST 2018
     */
    int insertSelective(TaskLink record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_link
     *
     * @mbg.generated Thu Jan 11 17:28:31 CST 2018
     */
    TaskLink selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_link
     *
     * @mbg.generated Thu Jan 11 17:28:31 CST 2018
     */
    int updateByPrimaryKeySelective(TaskLink record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_link
     *
     * @mbg.generated Thu Jan 11 17:28:31 CST 2018
     */
    int updateByPrimaryKey(TaskLink record);
}