package com.idata.gtd.dao;

import com.idata.gtd.entity.TplGroup;

public interface TplGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tpl_group
     *
     * @mbg.generated Thu Jan 11 17:28:31 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tpl_group
     *
     * @mbg.generated Thu Jan 11 17:28:31 CST 2018
     */
    int insert(TplGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tpl_group
     *
     * @mbg.generated Thu Jan 11 17:28:31 CST 2018
     */
    int insertSelective(TplGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tpl_group
     *
     * @mbg.generated Thu Jan 11 17:28:31 CST 2018
     */
    TplGroup selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tpl_group
     *
     * @mbg.generated Thu Jan 11 17:28:31 CST 2018
     */
    int updateByPrimaryKeySelective(TplGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tpl_group
     *
     * @mbg.generated Thu Jan 11 17:28:31 CST 2018
     */
    int updateByPrimaryKey(TplGroup record);
}