package com.idata.gtd.dao;

import com.idata.gtd.entity.TplProject;

public interface TplProjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tpl_project
     *
     * @mbg.generated Thu Jan 11 17:28:31 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tpl_project
     *
     * @mbg.generated Thu Jan 11 17:28:31 CST 2018
     */
    int insert(TplProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tpl_project
     *
     * @mbg.generated Thu Jan 11 17:28:31 CST 2018
     */
    int insertSelective(TplProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tpl_project
     *
     * @mbg.generated Thu Jan 11 17:28:31 CST 2018
     */
    TplProject selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tpl_project
     *
     * @mbg.generated Thu Jan 11 17:28:31 CST 2018
     */
    int updateByPrimaryKeySelective(TplProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tpl_project
     *
     * @mbg.generated Thu Jan 11 17:28:31 CST 2018
     */
    int updateByPrimaryKey(TplProject record);
}