package com.idata.gtd.dao;

import com.idata.gtd.entity.TplStage;

public interface TplStageMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tpl_stage
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tpl_stage
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	int insert(TplStage record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tpl_stage
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	int insertSelective(TplStage record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tpl_stage
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	TplStage selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tpl_stage
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	int updateByPrimaryKeySelective(TplStage record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tpl_stage
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	int updateByPrimaryKey(TplStage record);
}