package com.idata.gtd.dao;

import com.idata.gtd.entity.VendorEmployee;

public interface VendorEmployeeMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table vendor_employee
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table vendor_employee
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	int insert(VendorEmployee record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table vendor_employee
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	int insertSelective(VendorEmployee record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table vendor_employee
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	VendorEmployee selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table vendor_employee
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	int updateByPrimaryKeySelective(VendorEmployee record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table vendor_employee
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	int updateByPrimaryKey(VendorEmployee record);
}