package com.idata.gtd.dao;

import com.idata.gtd.entity.Vendor;

public interface VendorMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table vendor
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table vendor
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	int insert(Vendor record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table vendor
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	int insertSelective(Vendor record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table vendor
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	Vendor selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table vendor
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	int updateByPrimaryKeySelective(Vendor record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table vendor
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	int updateByPrimaryKey(Vendor record);
}