package com.idata.gtd.entity;

public class Admin {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.root_name
     *
     * @mbg.generated Thu Jan 11 17:28:31 CST 2018
     */
    private String rootName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.login_name
     *
     * @mbg.generated Thu Jan 11 17:28:31 CST 2018
     */
    private String loginName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.password
     *
     * @mbg.generated Thu Jan 11 17:28:31 CST 2018
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.root_name
     *
     * @return the value of admin.root_name
     *
     * @mbg.generated Thu Jan 11 17:28:31 CST 2018
     */
    public String getRootName() {
        return rootName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.root_name
     *
     * @param rootName the value for admin.root_name
     *
     * @mbg.generated Thu Jan 11 17:28:31 CST 2018
     */
    public void setRootName(String rootName) {
        this.rootName = rootName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.login_name
     *
     * @return the value of admin.login_name
     *
     * @mbg.generated Thu Jan 11 17:28:31 CST 2018
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.login_name
     *
     * @param loginName the value for admin.login_name
     *
     * @mbg.generated Thu Jan 11 17:28:31 CST 2018
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.password
     *
     * @return the value of admin.password
     *
     * @mbg.generated Thu Jan 11 17:28:31 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.password
     *
     * @param password the value for admin.password
     *
     * @mbg.generated Thu Jan 11 17:28:31 CST 2018
     */
    public void setPassword(String password) {
        this.password = password;
    }
}