package com.idata.gtd.entity;

public class Department {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column department.id
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column department.dep_name
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	private String depName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column department.dep_desc
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	private String depDesc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column department.parent_id
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	private Integer parentId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column department.id
	 * @return  the value of department.id
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column department.id
	 * @param id  the value for department.id
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column department.dep_name
	 * @return  the value of department.dep_name
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public String getDepName() {
		return depName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column department.dep_name
	 * @param depName  the value for department.dep_name
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public void setDepName(String depName) {
		this.depName = depName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column department.dep_desc
	 * @return  the value of department.dep_desc
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public String getDepDesc() {
		return depDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column department.dep_desc
	 * @param depDesc  the value for department.dep_desc
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public void setDepDesc(String depDesc) {
		this.depDesc = depDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column department.parent_id
	 * @return  the value of department.parent_id
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public Integer getParentId() {
		return parentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column department.parent_id
	 * @param parentId  the value for department.parent_id
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public void setParentId(Integer parentId) {
		this.parentId = parentId;
	}
}