package com.idata.gtd.entity;

import java.util.Date;

public class DocumentVersion {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column document_version.id
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column document_version.doc_id
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	private Integer docId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column document_version.owner_staff_id
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	private Integer ownerStaffId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column document_version.upload_date
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	private Date uploadDate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column document_version.id
	 * @return  the value of document_version.id
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column document_version.id
	 * @param id  the value for document_version.id
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column document_version.doc_id
	 * @return  the value of document_version.doc_id
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public Integer getDocId() {
		return docId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column document_version.doc_id
	 * @param docId  the value for document_version.doc_id
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public void setDocId(Integer docId) {
		this.docId = docId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column document_version.owner_staff_id
	 * @return  the value of document_version.owner_staff_id
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public Integer getOwnerStaffId() {
		return ownerStaffId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column document_version.owner_staff_id
	 * @param ownerStaffId  the value for document_version.owner_staff_id
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public void setOwnerStaffId(Integer ownerStaffId) {
		this.ownerStaffId = ownerStaffId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column document_version.upload_date
	 * @return  the value of document_version.upload_date
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public Date getUploadDate() {
		return uploadDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column document_version.upload_date
	 * @param uploadDate  the value for document_version.upload_date
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public void setUploadDate(Date uploadDate) {
		this.uploadDate = uploadDate;
	}
}