package com.idata.gtd.entity;

public class Document {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column document.id
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column document.document_name
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	private String documentName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column document.belong_to
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	private String belongTo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column document.source_id
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	private Integer sourceId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column document.id
	 * @return  the value of document.id
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column document.id
	 * @param id  the value for document.id
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column document.document_name
	 * @return  the value of document.document_name
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public String getDocumentName() {
		return documentName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column document.document_name
	 * @param documentName  the value for document.document_name
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public void setDocumentName(String documentName) {
		this.documentName = documentName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column document.belong_to
	 * @return  the value of document.belong_to
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public String getBelongTo() {
		return belongTo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column document.belong_to
	 * @param belongTo  the value for document.belong_to
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public void setBelongTo(String belongTo) {
		this.belongTo = belongTo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column document.source_id
	 * @return  the value of document.source_id
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public Integer getSourceId() {
		return sourceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column document.source_id
	 * @param sourceId  the value for document.source_id
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public void setSourceId(Integer sourceId) {
		this.sourceId = sourceId;
	}
}