package com.idata.gtd.entity;

public class Employee {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.id
     *
     * @mbg.generated Thu Jan 11 17:28:31 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.dep_id
     *
     * @mbg.generated Thu Jan 11 17:28:31 CST 2018
     */
    private Integer depId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.emp_name
     *
     * @mbg.generated Thu Jan 11 17:28:31 CST 2018
     */
    private String empName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.emp_gender
     *
     * @mbg.generated Thu Jan 11 17:28:31 CST 2018
     */
    private String empGender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.emp_mobile
     *
     * @mbg.generated Thu Jan 11 17:28:31 CST 2018
     */
    private String empMobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.emp_email
     *
     * @mbg.generated Thu Jan 11 17:28:31 CST 2018
     */
    private String empEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.emp_title
     *
     * @mbg.generated Thu Jan 11 17:28:31 CST 2018
     */
    private String empTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.emp_grade
     *
     * @mbg.generated Thu Jan 11 17:28:31 CST 2018
     */
    private String empGrade;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.id
     *
     * @return the value of employee.id
     *
     * @mbg.generated Thu Jan 11 17:28:31 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.id
     *
     * @param id the value for employee.id
     *
     * @mbg.generated Thu Jan 11 17:28:31 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.dep_id
     *
     * @return the value of employee.dep_id
     *
     * @mbg.generated Thu Jan 11 17:28:31 CST 2018
     */
    public Integer getDepId() {
        return depId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.dep_id
     *
     * @param depId the value for employee.dep_id
     *
     * @mbg.generated Thu Jan 11 17:28:31 CST 2018
     */
    public void setDepId(Integer depId) {
        this.depId = depId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.emp_name
     *
     * @return the value of employee.emp_name
     *
     * @mbg.generated Thu Jan 11 17:28:31 CST 2018
     */
    public String getEmpName() {
        return empName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.emp_name
     *
     * @param empName the value for employee.emp_name
     *
     * @mbg.generated Thu Jan 11 17:28:31 CST 2018
     */
    public void setEmpName(String empName) {
        this.empName = empName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.emp_gender
     *
     * @return the value of employee.emp_gender
     *
     * @mbg.generated Thu Jan 11 17:28:31 CST 2018
     */
    public String getEmpGender() {
        return empGender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.emp_gender
     *
     * @param empGender the value for employee.emp_gender
     *
     * @mbg.generated Thu Jan 11 17:28:31 CST 2018
     */
    public void setEmpGender(String empGender) {
        this.empGender = empGender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.emp_mobile
     *
     * @return the value of employee.emp_mobile
     *
     * @mbg.generated Thu Jan 11 17:28:31 CST 2018
     */
    public String getEmpMobile() {
        return empMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.emp_mobile
     *
     * @param empMobile the value for employee.emp_mobile
     *
     * @mbg.generated Thu Jan 11 17:28:31 CST 2018
     */
    public void setEmpMobile(String empMobile) {
        this.empMobile = empMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.emp_email
     *
     * @return the value of employee.emp_email
     *
     * @mbg.generated Thu Jan 11 17:28:31 CST 2018
     */
    public String getEmpEmail() {
        return empEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.emp_email
     *
     * @param empEmail the value for employee.emp_email
     *
     * @mbg.generated Thu Jan 11 17:28:31 CST 2018
     */
    public void setEmpEmail(String empEmail) {
        this.empEmail = empEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.emp_title
     *
     * @return the value of employee.emp_title
     *
     * @mbg.generated Thu Jan 11 17:28:31 CST 2018
     */
    public String getEmpTitle() {
        return empTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.emp_title
     *
     * @param empTitle the value for employee.emp_title
     *
     * @mbg.generated Thu Jan 11 17:28:31 CST 2018
     */
    public void setEmpTitle(String empTitle) {
        this.empTitle = empTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.emp_grade
     *
     * @return the value of employee.emp_grade
     *
     * @mbg.generated Thu Jan 11 17:28:31 CST 2018
     */
    public String getEmpGrade() {
        return empGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.emp_grade
     *
     * @param empGrade the value for employee.emp_grade
     *
     * @mbg.generated Thu Jan 11 17:28:31 CST 2018
     */
    public void setEmpGrade(String empGrade) {
        this.empGrade = empGrade;
    }
}