package com.idata.gtd.entity;

import java.util.Date;

public class Log {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column log.id
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column log.actor
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	private String actor;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column log.op_time
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	private Date opTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column log.action
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	private String action;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column log.target
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	private String target;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column log.id
	 * @return  the value of log.id
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column log.id
	 * @param id  the value for log.id
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column log.actor
	 * @return  the value of log.actor
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public String getActor() {
		return actor;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column log.actor
	 * @param actor  the value for log.actor
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public void setActor(String actor) {
		this.actor = actor;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column log.op_time
	 * @return  the value of log.op_time
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public Date getOpTime() {
		return opTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column log.op_time
	 * @param opTime  the value for log.op_time
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public void setOpTime(Date opTime) {
		this.opTime = opTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column log.action
	 * @return  the value of log.action
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public String getAction() {
		return action;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column log.action
	 * @param action  the value for log.action
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public void setAction(String action) {
		this.action = action;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column log.target
	 * @return  the value of log.target
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public String getTarget() {
		return target;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column log.target
	 * @param target  the value for log.target
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public void setTarget(String target) {
		this.target = target;
	}
}