package com.idata.gtd.entity;

public class ParamKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column param_key.id
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column param_key.param_key
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	private String paramKey;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column param_key.data_type
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	private String dataType;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column param_key.id
	 * @return  the value of param_key.id
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column param_key.id
	 * @param id  the value for param_key.id
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column param_key.param_key
	 * @return  the value of param_key.param_key
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public String getParamKey() {
		return paramKey;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column param_key.param_key
	 * @param paramKey  the value for param_key.param_key
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public void setParamKey(String paramKey) {
		this.paramKey = paramKey;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column param_key.data_type
	 * @return  the value of param_key.data_type
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public String getDataType() {
		return dataType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column param_key.data_type
	 * @param dataType  the value for param_key.data_type
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public void setDataType(String dataType) {
		this.dataType = dataType;
	}
}