package com.idata.gtd.entity;

public class ParamValue {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column param_value.id
     *
     * @mbg.generated Thu Jan 11 17:28:31 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column param_value.param_id
     *
     * @mbg.generated Thu Jan 11 17:28:31 CST 2018
     */
    private Integer paramId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column param_value.param_value
     *
     * @mbg.generated Thu Jan 11 17:28:31 CST 2018
     */
    private String paramValue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column param_value.id
     *
     * @return the value of param_value.id
     *
     * @mbg.generated Thu Jan 11 17:28:31 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column param_value.id
     *
     * @param id the value for param_value.id
     *
     * @mbg.generated Thu Jan 11 17:28:31 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column param_value.param_id
     *
     * @return the value of param_value.param_id
     *
     * @mbg.generated Thu Jan 11 17:28:31 CST 2018
     */
    public Integer getParamId() {
        return paramId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column param_value.param_id
     *
     * @param paramId the value for param_value.param_id
     *
     * @mbg.generated Thu Jan 11 17:28:31 CST 2018
     */
    public void setParamId(Integer paramId) {
        this.paramId = paramId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column param_value.param_value
     *
     * @return the value of param_value.param_value
     *
     * @mbg.generated Thu Jan 11 17:28:31 CST 2018
     */
    public String getParamValue() {
        return paramValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column param_value.param_value
     *
     * @param paramValue the value for param_value.param_value
     *
     * @mbg.generated Thu Jan 11 17:28:31 CST 2018
     */
    public void setParamValue(String paramValue) {
        this.paramValue = paramValue;
    }
}