package com.idata.gtd.entity;

import java.util.Date;

public class ProjectTask {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_task.id
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_task.stage_id
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	private Integer stageId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_task.task_name
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	private String taskName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_task.task_desc
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	private String taskDesc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_task.from_date
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	private Date fromDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_task.end_date
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	private Date endDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_task.priority
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	private Integer priority;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_task.progress
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	private Integer progress;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_task.state
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	private Integer state;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_task.assign_staff_id
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	private Integer assignStaffId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_task.actor_staff_id
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	private Integer actorStaffId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_task.plan_workload
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	private Integer planWorkload;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_task.real_workload
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	private Integer realWorkload;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_task.is_delay
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	private Integer isDelay;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_task.delay_reason
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	private String delayReason;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_task.parent_id
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	private Integer parentId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_task.id
	 * @return  the value of project_task.id
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_task.id
	 * @param id  the value for project_task.id
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_task.stage_id
	 * @return  the value of project_task.stage_id
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public Integer getStageId() {
		return stageId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_task.stage_id
	 * @param stageId  the value for project_task.stage_id
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public void setStageId(Integer stageId) {
		this.stageId = stageId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_task.task_name
	 * @return  the value of project_task.task_name
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public String getTaskName() {
		return taskName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_task.task_name
	 * @param taskName  the value for project_task.task_name
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public void setTaskName(String taskName) {
		this.taskName = taskName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_task.task_desc
	 * @return  the value of project_task.task_desc
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public String getTaskDesc() {
		return taskDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_task.task_desc
	 * @param taskDesc  the value for project_task.task_desc
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public void setTaskDesc(String taskDesc) {
		this.taskDesc = taskDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_task.from_date
	 * @return  the value of project_task.from_date
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public Date getFromDate() {
		return fromDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_task.from_date
	 * @param fromDate  the value for project_task.from_date
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public void setFromDate(Date fromDate) {
		this.fromDate = fromDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_task.end_date
	 * @return  the value of project_task.end_date
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public Date getEndDate() {
		return endDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_task.end_date
	 * @param endDate  the value for project_task.end_date
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_task.priority
	 * @return  the value of project_task.priority
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public Integer getPriority() {
		return priority;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_task.priority
	 * @param priority  the value for project_task.priority
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public void setPriority(Integer priority) {
		this.priority = priority;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_task.progress
	 * @return  the value of project_task.progress
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public Integer getProgress() {
		return progress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_task.progress
	 * @param progress  the value for project_task.progress
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public void setProgress(Integer progress) {
		this.progress = progress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_task.state
	 * @return  the value of project_task.state
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public Integer getState() {
		return state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_task.state
	 * @param state  the value for project_task.state
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public void setState(Integer state) {
		this.state = state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_task.assign_staff_id
	 * @return  the value of project_task.assign_staff_id
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public Integer getAssignStaffId() {
		return assignStaffId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_task.assign_staff_id
	 * @param assignStaffId  the value for project_task.assign_staff_id
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public void setAssignStaffId(Integer assignStaffId) {
		this.assignStaffId = assignStaffId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_task.actor_staff_id
	 * @return  the value of project_task.actor_staff_id
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public Integer getActorStaffId() {
		return actorStaffId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_task.actor_staff_id
	 * @param actorStaffId  the value for project_task.actor_staff_id
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public void setActorStaffId(Integer actorStaffId) {
		this.actorStaffId = actorStaffId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_task.plan_workload
	 * @return  the value of project_task.plan_workload
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public Integer getPlanWorkload() {
		return planWorkload;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_task.plan_workload
	 * @param planWorkload  the value for project_task.plan_workload
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public void setPlanWorkload(Integer planWorkload) {
		this.planWorkload = planWorkload;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_task.real_workload
	 * @return  the value of project_task.real_workload
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public Integer getRealWorkload() {
		return realWorkload;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_task.real_workload
	 * @param realWorkload  the value for project_task.real_workload
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public void setRealWorkload(Integer realWorkload) {
		this.realWorkload = realWorkload;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_task.is_delay
	 * @return  the value of project_task.is_delay
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public Integer getIsDelay() {
		return isDelay;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_task.is_delay
	 * @param isDelay  the value for project_task.is_delay
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public void setIsDelay(Integer isDelay) {
		this.isDelay = isDelay;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_task.delay_reason
	 * @return  the value of project_task.delay_reason
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public String getDelayReason() {
		return delayReason;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_task.delay_reason
	 * @param delayReason  the value for project_task.delay_reason
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public void setDelayReason(String delayReason) {
		this.delayReason = delayReason;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_task.parent_id
	 * @return  the value of project_task.parent_id
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public Integer getParentId() {
		return parentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_task.parent_id
	 * @param parentId  the value for project_task.parent_id
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public void setParentId(Integer parentId) {
		this.parentId = parentId;
	}
}