package com.idata.gtd.entity;

public class ProjectContract {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_contract.id
     *
     * @mbg.generated Thu Jan 11 17:28:31 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_contract.project_id
     *
     * @mbg.generated Thu Jan 11 17:28:31 CST 2018
     */
    private Integer projectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_contract.vendor_id
     *
     * @mbg.generated Thu Jan 11 17:28:31 CST 2018
     */
    private Integer vendorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_contract.contract_name
     *
     * @mbg.generated Thu Jan 11 17:28:31 CST 2018
     */
    private String contractName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_contract.id
     *
     * @return the value of project_contract.id
     *
     * @mbg.generated Thu Jan 11 17:28:31 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_contract.id
     *
     * @param id the value for project_contract.id
     *
     * @mbg.generated Thu Jan 11 17:28:31 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_contract.project_id
     *
     * @return the value of project_contract.project_id
     *
     * @mbg.generated Thu Jan 11 17:28:31 CST 2018
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_contract.project_id
     *
     * @param projectId the value for project_contract.project_id
     *
     * @mbg.generated Thu Jan 11 17:28:31 CST 2018
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_contract.vendor_id
     *
     * @return the value of project_contract.vendor_id
     *
     * @mbg.generated Thu Jan 11 17:28:31 CST 2018
     */
    public Integer getVendorId() {
        return vendorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_contract.vendor_id
     *
     * @param vendorId the value for project_contract.vendor_id
     *
     * @mbg.generated Thu Jan 11 17:28:31 CST 2018
     */
    public void setVendorId(Integer vendorId) {
        this.vendorId = vendorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_contract.contract_name
     *
     * @return the value of project_contract.contract_name
     *
     * @mbg.generated Thu Jan 11 17:28:31 CST 2018
     */
    public String getContractName() {
        return contractName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_contract.contract_name
     *
     * @param contractName the value for project_contract.contract_name
     *
     * @mbg.generated Thu Jan 11 17:28:31 CST 2018
     */
    public void setContractName(String contractName) {
        this.contractName = contractName;
    }
}