package com.idata.gtd.entity;

public class ProjectStaff {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_staff.id
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_staff.is_vendor
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	private Integer isVendor;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_staff.group_id
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	private Integer groupId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_staff.emp_id
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	private Integer empId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_staff.staff_name
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	private String staffName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_staff.staff_email
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	private String staffEmail;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_staff.staff_mobile
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	private String staffMobile;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_staff.password
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	private String password;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_staff.id
	 * @return  the value of project_staff.id
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_staff.id
	 * @param id  the value for project_staff.id
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_staff.is_vendor
	 * @return  the value of project_staff.is_vendor
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public Integer getIsVendor() {
		return isVendor;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_staff.is_vendor
	 * @param isVendor  the value for project_staff.is_vendor
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public void setIsVendor(Integer isVendor) {
		this.isVendor = isVendor;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_staff.group_id
	 * @return  the value of project_staff.group_id
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public Integer getGroupId() {
		return groupId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_staff.group_id
	 * @param groupId  the value for project_staff.group_id
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public void setGroupId(Integer groupId) {
		this.groupId = groupId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_staff.emp_id
	 * @return  the value of project_staff.emp_id
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public Integer getEmpId() {
		return empId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_staff.emp_id
	 * @param empId  the value for project_staff.emp_id
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public void setEmpId(Integer empId) {
		this.empId = empId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_staff.staff_name
	 * @return  the value of project_staff.staff_name
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public String getStaffName() {
		return staffName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_staff.staff_name
	 * @param staffName  the value for project_staff.staff_name
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public void setStaffName(String staffName) {
		this.staffName = staffName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_staff.staff_email
	 * @return  the value of project_staff.staff_email
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public String getStaffEmail() {
		return staffEmail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_staff.staff_email
	 * @param staffEmail  the value for project_staff.staff_email
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public void setStaffEmail(String staffEmail) {
		this.staffEmail = staffEmail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_staff.staff_mobile
	 * @return  the value of project_staff.staff_mobile
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public String getStaffMobile() {
		return staffMobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_staff.staff_mobile
	 * @param staffMobile  the value for project_staff.staff_mobile
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public void setStaffMobile(String staffMobile) {
		this.staffMobile = staffMobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_staff.password
	 * @return  the value of project_staff.password
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_staff.password
	 * @param password  the value for project_staff.password
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public void setPassword(String password) {
		this.password = password;
	}
}