package com.idata.gtd.entity;

import java.util.Date;

public class Project {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project.id
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project.project_name
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	private String projectName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project.project_desc
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	private String projectDesc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project.category
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	private String category;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project.is_key
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	private Integer isKey;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project.is_forzen
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	private Integer isForzen;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project.create_date
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	private Date createDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project.start_date
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	private Date startDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project.end_date
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	private Date endDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project.dep_id
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	private Integer depId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project.icon
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	private String icon;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project.amount
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	private Integer amount;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project.id
	 * @return  the value of project.id
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project.id
	 * @param id  the value for project.id
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project.project_name
	 * @return  the value of project.project_name
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public String getProjectName() {
		return projectName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project.project_name
	 * @param projectName  the value for project.project_name
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project.project_desc
	 * @return  the value of project.project_desc
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public String getProjectDesc() {
		return projectDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project.project_desc
	 * @param projectDesc  the value for project.project_desc
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public void setProjectDesc(String projectDesc) {
		this.projectDesc = projectDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project.category
	 * @return  the value of project.category
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public String getCategory() {
		return category;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project.category
	 * @param category  the value for project.category
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public void setCategory(String category) {
		this.category = category;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project.is_key
	 * @return  the value of project.is_key
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public Integer getIsKey() {
		return isKey;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project.is_key
	 * @param isKey  the value for project.is_key
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public void setIsKey(Integer isKey) {
		this.isKey = isKey;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project.is_forzen
	 * @return  the value of project.is_forzen
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public Integer getIsForzen() {
		return isForzen;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project.is_forzen
	 * @param isForzen  the value for project.is_forzen
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public void setIsForzen(Integer isForzen) {
		this.isForzen = isForzen;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project.create_date
	 * @return  the value of project.create_date
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project.create_date
	 * @param createDate  the value for project.create_date
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project.start_date
	 * @return  the value of project.start_date
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public Date getStartDate() {
		return startDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project.start_date
	 * @param startDate  the value for project.start_date
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project.end_date
	 * @return  the value of project.end_date
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public Date getEndDate() {
		return endDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project.end_date
	 * @param endDate  the value for project.end_date
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project.dep_id
	 * @return  the value of project.dep_id
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public Integer getDepId() {
		return depId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project.dep_id
	 * @param depId  the value for project.dep_id
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public void setDepId(Integer depId) {
		this.depId = depId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project.icon
	 * @return  the value of project.icon
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public String getIcon() {
		return icon;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project.icon
	 * @param icon  the value for project.icon
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public void setIcon(String icon) {
		this.icon = icon;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project.amount
	 * @return  the value of project.amount
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public Integer getAmount() {
		return amount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project.amount
	 * @param amount  the value for project.amount
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public void setAmount(Integer amount) {
		this.amount = amount;
	}
}