package com.idata.gtd.entity;

public class ProjectTag {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_tag.id
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_tag.project_id
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	private Integer projectId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_tag.tag_name
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	private String tagName;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_tag.id
	 * @return  the value of project_tag.id
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_tag.id
	 * @param id  the value for project_tag.id
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_tag.project_id
	 * @return  the value of project_tag.project_id
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public Integer getProjectId() {
		return projectId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_tag.project_id
	 * @param projectId  the value for project_tag.project_id
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public void setProjectId(Integer projectId) {
		this.projectId = projectId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_tag.tag_name
	 * @return  the value of project_tag.tag_name
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public String getTagName() {
		return tagName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_tag.tag_name
	 * @param tagName  the value for project_tag.tag_name
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public void setTagName(String tagName) {
		this.tagName = tagName;
	}
}