package com.idata.gtd.entity;

public class TaskLink {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_link.id
     *
     * @mbg.generated Thu Jan 11 17:28:31 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_link.from_task
     *
     * @mbg.generated Thu Jan 11 17:28:31 CST 2018
     */
    private String fromTask;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_link.to_task
     *
     * @mbg.generated Thu Jan 11 17:28:31 CST 2018
     */
    private String toTask;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_link.status
     *
     * @mbg.generated Thu Jan 11 17:28:31 CST 2018
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_link.id
     *
     * @return the value of task_link.id
     *
     * @mbg.generated Thu Jan 11 17:28:31 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_link.id
     *
     * @param id the value for task_link.id
     *
     * @mbg.generated Thu Jan 11 17:28:31 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_link.from_task
     *
     * @return the value of task_link.from_task
     *
     * @mbg.generated Thu Jan 11 17:28:31 CST 2018
     */
    public String getFromTask() {
        return fromTask;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_link.from_task
     *
     * @param fromTask the value for task_link.from_task
     *
     * @mbg.generated Thu Jan 11 17:28:31 CST 2018
     */
    public void setFromTask(String fromTask) {
        this.fromTask = fromTask;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_link.to_task
     *
     * @return the value of task_link.to_task
     *
     * @mbg.generated Thu Jan 11 17:28:31 CST 2018
     */
    public String getToTask() {
        return toTask;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_link.to_task
     *
     * @param toTask the value for task_link.to_task
     *
     * @mbg.generated Thu Jan 11 17:28:31 CST 2018
     */
    public void setToTask(String toTask) {
        this.toTask = toTask;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_link.status
     *
     * @return the value of task_link.status
     *
     * @mbg.generated Thu Jan 11 17:28:31 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_link.status
     *
     * @param status the value for task_link.status
     *
     * @mbg.generated Thu Jan 11 17:28:31 CST 2018
     */
    public void setStatus(String status) {
        this.status = status;
    }
}