package com.idata.gtd.entity;

public class TplGroup {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tpl_group.id
     *
     * @mbg.generated Thu Jan 11 17:28:31 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tpl_group.tpl_id
     *
     * @mbg.generated Thu Jan 11 17:28:31 CST 2018
     */
    private Integer tplId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tpl_group.group_name
     *
     * @mbg.generated Thu Jan 11 17:28:31 CST 2018
     */
    private String groupName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tpl_group.parent_id
     *
     * @mbg.generated Thu Jan 11 17:28:31 CST 2018
     */
    private Integer parentId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tpl_group.id
     *
     * @return the value of tpl_group.id
     *
     * @mbg.generated Thu Jan 11 17:28:31 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tpl_group.id
     *
     * @param id the value for tpl_group.id
     *
     * @mbg.generated Thu Jan 11 17:28:31 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tpl_group.tpl_id
     *
     * @return the value of tpl_group.tpl_id
     *
     * @mbg.generated Thu Jan 11 17:28:31 CST 2018
     */
    public Integer getTplId() {
        return tplId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tpl_group.tpl_id
     *
     * @param tplId the value for tpl_group.tpl_id
     *
     * @mbg.generated Thu Jan 11 17:28:31 CST 2018
     */
    public void setTplId(Integer tplId) {
        this.tplId = tplId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tpl_group.group_name
     *
     * @return the value of tpl_group.group_name
     *
     * @mbg.generated Thu Jan 11 17:28:31 CST 2018
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tpl_group.group_name
     *
     * @param groupName the value for tpl_group.group_name
     *
     * @mbg.generated Thu Jan 11 17:28:31 CST 2018
     */
    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tpl_group.parent_id
     *
     * @return the value of tpl_group.parent_id
     *
     * @mbg.generated Thu Jan 11 17:28:31 CST 2018
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tpl_group.parent_id
     *
     * @param parentId the value for tpl_group.parent_id
     *
     * @mbg.generated Thu Jan 11 17:28:31 CST 2018
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }
}