package com.idata.gtd.entity;

public class TplProject {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tpl_project.id
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tpl_project.tpl_name
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	private String tplName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tpl_project.tpl_category
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	private String tplCategory;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tpl_project.id
	 * @return  the value of tpl_project.id
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tpl_project.id
	 * @param id  the value for tpl_project.id
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tpl_project.tpl_name
	 * @return  the value of tpl_project.tpl_name
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public String getTplName() {
		return tplName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tpl_project.tpl_name
	 * @param tplName  the value for tpl_project.tpl_name
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public void setTplName(String tplName) {
		this.tplName = tplName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tpl_project.tpl_category
	 * @return  the value of tpl_project.tpl_category
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public String getTplCategory() {
		return tplCategory;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tpl_project.tpl_category
	 * @param tplCategory  the value for tpl_project.tpl_category
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public void setTplCategory(String tplCategory) {
		this.tplCategory = tplCategory;
	}
}