package com.idata.gtd.entity;

public class TplStage {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tpl_stage.id
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tpl_stage.tpl_id
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	private Integer tplId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tpl_stage.stage_name
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	private String stageName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tpl_stage.parent_id
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	private Integer parentId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tpl_stage.id
	 * @return  the value of tpl_stage.id
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tpl_stage.id
	 * @param id  the value for tpl_stage.id
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tpl_stage.tpl_id
	 * @return  the value of tpl_stage.tpl_id
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public Integer getTplId() {
		return tplId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tpl_stage.tpl_id
	 * @param tplId  the value for tpl_stage.tpl_id
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public void setTplId(Integer tplId) {
		this.tplId = tplId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tpl_stage.stage_name
	 * @return  the value of tpl_stage.stage_name
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public String getStageName() {
		return stageName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tpl_stage.stage_name
	 * @param stageName  the value for tpl_stage.stage_name
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public void setStageName(String stageName) {
		this.stageName = stageName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tpl_stage.parent_id
	 * @return  the value of tpl_stage.parent_id
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public Integer getParentId() {
		return parentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tpl_stage.parent_id
	 * @param parentId  the value for tpl_stage.parent_id
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public void setParentId(Integer parentId) {
		this.parentId = parentId;
	}
}