package com.idata.gtd.entity;

public class Vendor {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column vendor.id
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column vendor.vendor_name
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	private String vendorName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column vendor.vendor_full_name
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	private String vendorFullName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column vendor.contact_name
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	private String contactName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column vendor.contact_mobile
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	private String contactMobile;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column vendor.id
	 * @return  the value of vendor.id
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column vendor.id
	 * @param id  the value for vendor.id
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column vendor.vendor_name
	 * @return  the value of vendor.vendor_name
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public String getVendorName() {
		return vendorName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column vendor.vendor_name
	 * @param vendorName  the value for vendor.vendor_name
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public void setVendorName(String vendorName) {
		this.vendorName = vendorName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column vendor.vendor_full_name
	 * @return  the value of vendor.vendor_full_name
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public String getVendorFullName() {
		return vendorFullName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column vendor.vendor_full_name
	 * @param vendorFullName  the value for vendor.vendor_full_name
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public void setVendorFullName(String vendorFullName) {
		this.vendorFullName = vendorFullName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column vendor.contact_name
	 * @return  the value of vendor.contact_name
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public String getContactName() {
		return contactName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column vendor.contact_name
	 * @param contactName  the value for vendor.contact_name
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public void setContactName(String contactName) {
		this.contactName = contactName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column vendor.contact_mobile
	 * @return  the value of vendor.contact_mobile
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public String getContactMobile() {
		return contactMobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column vendor.contact_mobile
	 * @param contactMobile  the value for vendor.contact_mobile
	 * @mbg.generated  Thu Jan 11 18:00:33 CST 2018
	 */
	public void setContactMobile(String contactMobile) {
		this.contactMobile = contactMobile;
	}
}